language: cpp

sudo: required

os:
  - osx

compiler:
  - gcc

before_install:
  # before we build cura we build all dependencies from source. At this point I was unable to find pre-built bins for osx deps, but check back with Ultimaker as they said they were working on this
  - export MACOSX_DEPLOYMENT_TARGET=10.7
  - export CC=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
  - export CXX=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
  - export CFLAGS=-I/usr/local/include
  - brew update && brew install llvm38 && brew install openssl && brew link --force --overwrite openssl


before_script:
  # if you want to use xcode > v8.0.0
  # - sudo ln -s /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild /Applications/Xcode.app/Contents/Developer/usr/bin/xcrun
  - git clone https://github.com/Ultimaker/cura-build-environment.git $HOME/cura-build-environment # replace with robo3d version
  - cd $HOME/cura-build-environment
  - mkdir build && cd $HOME/cura-build-environment/build
  - cmake .. -DCMAKE_PREFIX_PATH=/opt/cura-build-environment -DCMAKE_BUILD_TYPE=Release -DINCLUDE_DEVEL=ON
  - make -j6
  - cd $HOME
  - mkdir build
  - cmake .. -DCMAKE_INSTALL_PREFIX=/opt/cura-build -DCMAKE_PREFIX_PATH=/opt/cura-build-environment -DCMAKE_BUILD_TYPE=Release

script: make -j6
